-- 人工基准 SQL（用于对照 run.py 自动生成结果）
-- 数据域：Olist 历史快照（约 2016-09 ~ 2018-10）

-- Q1: 2017 年 GMV 是多少？按月和各州排名的趋势怎样？
SELECT SUM(`total_gmv`) AS `gmv_2017` FROM `mv_monthly_sales` WHERE `year_month` LIKE '2017-%';
SELECT `year_month`, `total_gmv`, `total_orders`, `avg_basket`, `total_freight` FROM `mv_monthly_sales` WHERE `year_month` LIKE '2017-%' ORDER BY `year_month`;
SELECT `year_month`, `customer_state`, `total_gmv`, ROW_NUMBER() OVER (PARTITION BY `year_month` ORDER BY `total_gmv` DESC) AS `state_rank_in_month` FROM `mv_state_sales` WHERE `year_month` LIKE '2017-%' ORDER BY `year_month`, `state_rank_in_month`;

-- Q2: 平台整体准时交付率是多少？哪些州延迟最严重？
SELECT SUM(CASE WHEN `order_delivered_customer_date` <= `order_estimated_delivery_date` THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0) AS `overall_on_time_rate` FROM `orders` WHERE `order_status` = 'delivered' AND `order_delivered_customer_date` IS NOT NULL AND `order_estimated_delivery_date` IS NOT NULL;
SELECT `customer_state`, SUM(`delayed_orders`) AS `total_delayed_orders` FROM `mv_delivery_perf` GROUP BY `customer_state` ORDER BY `total_delayed_orders` DESC LIMIT 10;

-- Q3: 哪种支付方式最受欢迎？平均分期数是多少？
SELECT `payment_type`, SUM(`total_transactions`) AS `total_transactions`, SUM(`avg_installments` * `total_transactions`) / NULLIF(SUM(`total_transactions`), 0) AS `weighted_avg_installments` FROM `mv_payment_dist` GROUP BY `payment_type` ORDER BY `total_transactions` DESC;
SELECT SUM(`avg_installments` * `total_transactions`) / NULLIF(SUM(`total_transactions`), 0) AS `overall_weighted_avg_installments` FROM `mv_payment_dist`;

-- Q4: 产品的重量、尺寸与运费之间有什么关系？
WITH `item_features` AS (SELECT `oi`.`order_id`, `oi`.`order_item_id`, `oi`.`freight_value`, `p`.`product_weight_g`, (`p`.`product_length_cm` * `p`.`product_height_cm` * `p`.`product_width_cm`) AS `product_volume_cm3` FROM `order_items` `oi` INNER JOIN `products` `p` ON `oi`.`product_id` = `p`.`product_id` WHERE `oi`.`freight_value` IS NOT NULL AND `p`.`product_weight_g` IS NOT NULL AND `p`.`product_length_cm` IS NOT NULL AND `p`.`product_height_cm` IS NOT NULL AND `p`.`product_width_cm` IS NOT NULL)
SELECT (COUNT(*) * SUM(`product_weight_g` * `freight_value`) - SUM(`product_weight_g`) * SUM(`freight_value`)) / NULLIF(SQRT((COUNT(*) * SUM(`product_weight_g` * `product_weight_g`) - POW(SUM(`product_weight_g`), 2)) * (COUNT(*) * SUM(`freight_value` * `freight_value`) - POW(SUM(`freight_value`), 2))), 0) AS `corr_weight_freight`, (COUNT(*) * SUM(`product_volume_cm3` * `freight_value`) - SUM(`product_volume_cm3`) * SUM(`freight_value`)) / NULLIF(SQRT((COUNT(*) * SUM(`product_volume_cm3` * `product_volume_cm3`) - POW(SUM(`product_volume_cm3`), 2)) * (COUNT(*) * SUM(`freight_value` * `freight_value`) - POW(SUM(`freight_value`), 2))), 0) AS `corr_volume_freight` FROM `item_features`;
SELECT CASE WHEN `p`.`product_weight_g` < 500 THEN '0-499g' WHEN `p`.`product_weight_g` < 1000 THEN '500-999g' WHEN `p`.`product_weight_g` < 2000 THEN '1000-1999g' WHEN `p`.`product_weight_g` < 5000 THEN '2000-4999g' ELSE '5000g+' END AS `weight_bucket`, AVG(`oi`.`freight_value`) AS `avg_freight_value`, COUNT(*) AS `item_count` FROM `order_items` `oi` INNER JOIN `products` `p` ON `oi`.`product_id` = `p`.`product_id` GROUP BY `weight_bucket` ORDER BY MIN(`p`.`product_weight_g`);

-- Q5: Top 10 差评品类是什么？
SELECT COALESCE(`pct`.`product_category_name_english`, `p`.`product_category_name`) AS `product_category`, COUNT(*) AS `bad_review_count`, COUNT(DISTINCT `o`.`order_id`) AS `bad_review_orders` FROM `order_reviews` `r` INNER JOIN `orders` `o` ON `r`.`order_id` = `o`.`order_id` INNER JOIN `order_items` `oi` ON `o`.`order_id` = `oi`.`order_id` INNER JOIN `products` `p` ON `oi`.`product_id` = `p`.`product_id` LEFT JOIN `product_category_name_translation` `pct` ON `p`.`product_category_name` = `pct`.`product_category_name` WHERE `r`.`review_score` <= 2 GROUP BY `product_category` ORDER BY `bad_review_count` DESC LIMIT 10;

-- Q6: 2017年哪个州的销售额最高？交付准时率是多少？哪种支付方式最受欢迎？
WITH `top_state` AS (SELECT `customer_state`, SUM(`total_gmv`) AS `gmv_2017` FROM `mv_state_sales` WHERE `year_month` LIKE '2017-%' GROUP BY `customer_state` ORDER BY `gmv_2017` DESC LIMIT 1), `state_on_time` AS (SELECT `c`.`customer_state`, SUM(CASE WHEN `o`.`order_delivered_customer_date` <= `o`.`order_estimated_delivery_date` THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0) AS `on_time_rate_2017` FROM `orders` `o` INNER JOIN `customers` `c` ON `o`.`customer_id` = `c`.`customer_id` INNER JOIN `top_state` `ts` ON `c`.`customer_state` = `ts`.`customer_state` WHERE `o`.`order_status` = 'delivered' AND `o`.`order_purchase_timestamp` >= '2017-01-01' AND `o`.`order_purchase_timestamp` < '2018-01-01' AND `o`.`order_delivered_customer_date` IS NOT NULL AND `o`.`order_estimated_delivery_date` IS NOT NULL GROUP BY `c`.`customer_state`), `state_top_payment` AS (SELECT `c`.`customer_state`, `p`.`payment_type`, COUNT(DISTINCT `o`.`order_id`) AS `transaction_count` FROM `orders` `o` INNER JOIN `customers` `c` ON `o`.`customer_id` = `c`.`customer_id` INNER JOIN `payments` `p` ON `o`.`order_id` = `p`.`order_id` INNER JOIN `top_state` `ts` ON `c`.`customer_state` = `ts`.`customer_state` WHERE `o`.`order_purchase_timestamp` >= '2017-01-01' AND `o`.`order_purchase_timestamp` < '2018-01-01' GROUP BY `c`.`customer_state`, `p`.`payment_type` ORDER BY `transaction_count` DESC LIMIT 1)
SELECT `ts`.`customer_state` AS `top_state_2017`, `ts`.`gmv_2017`, `sot`.`on_time_rate_2017`, `stp`.`payment_type` AS `most_popular_payment_type`, `stp`.`transaction_count` AS `payment_transactions` FROM `top_state` `ts` LEFT JOIN `state_on_time` `sot` ON `ts`.`customer_state` = `sot`.`customer_state` LEFT JOIN `state_top_payment` `stp` ON `ts`.`customer_state` = `stp`.`customer_state`;

-- Q7: 哪些卖家的差评率最高？
SELECT `oi`.`seller_id`, COUNT(DISTINCT CASE WHEN `r`.`review_score` IS NOT NULL THEN `o`.`order_id` END) AS `reviewed_orders`, COUNT(DISTINCT CASE WHEN `r`.`review_score` <= 2 THEN `o`.`order_id` END) AS `bad_review_orders`, COUNT(DISTINCT CASE WHEN `r`.`review_score` <= 2 THEN `o`.`order_id` END) / NULLIF(COUNT(DISTINCT CASE WHEN `r`.`review_score` IS NOT NULL THEN `o`.`order_id` END), 0) AS `bad_review_rate` FROM `orders` `o` INNER JOIN `order_items` `oi` ON `o`.`order_id` = `oi`.`order_id` LEFT JOIN `order_reviews` `r` ON `o`.`order_id` = `r`.`order_id` GROUP BY `oi`.`seller_id` HAVING `reviewed_orders` >= 20 ORDER BY `bad_review_rate` DESC, `reviewed_orders` DESC LIMIT 20;
